// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gagzfzcfrezfurwhdbhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhZ3pmemNmcmV6ZnVyd2hkYmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzM2NDYsImV4cCI6MjA1OTEwOTY0Nn0.ICm3PZQo51XxH88B-Vtwt7jp1vaHJyIbuEyDdYX4kL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);